version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:16.12
      # https://github.com/cypress-io/cypress-docker-images
      - image: cypress/base:14
        environment:
          TERM: xterm
    steps:
      - checkout
      - run:
          name: Install base packages (for Cypress)
          command: |
            sudo apt-get update
            sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - run:
          name: Update npm
          command: |
            sudo npm install -g npm@latest
      - run:
          name: Update Yarn
          command: |
            sudo apt-get update && sudo apt-get install apt-transport-https -y
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            sudo apt-get update -y && sudo apt-get install yarn -y
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: yarn install
          command: yarn install
      #   - run:
      #       name: Install Cypress
      #       command: npx cypress install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
            # Cypress
            - ~/.cache
      #   - run:
      #       name: Execute Jest
      #       command: yarn test:unit
      - run:
          # https://cli.vuejs.org/core-plugins/e2e-cypress.html
          name: Execute Cypress
          command: yarn test:e2e --headless
      # - run:
      #     name: Code coverage
      #     command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          destination: tests
      - store_artifacts:
          path: coverage
          destination: coverage
      - store_test_results:
          path: test-results.xml
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
