name: Challenging Vue.js
on:
  push:
jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.1'
          cache: 'yarn'
      - name: yarn install
        run: |
          yarn install --frozen-lockfile
      - name: Unit test
        run: |
          yarn test:unit
      - name: E2E test
        run: |
          yarn test:e2e --headless
