name: Challenging Vue.js
on:
  push:
jobs:
  continuous_integration:
    name: lets_continuous_integration
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.x'
          registry-url: 'https://registry.npmjs.org'
      - name: yarn install
        run: |
          yarn install
      # - name: test
      #   run: |
      #     yarn test
